AVD Data Model for EVPN/VXLAN Deployment Guide - Domain A
aristanetworks/aclabs pull request #61
Opened 2024-11-16 22:43 UTC by MitchV85

## Change Summary

- Add AVD data model for EVPN/VXLAN Domain A
- Update the `techlib-vxlan-domain-a` container to use `lab-base:python3.11-avd-v5.0.0-clab0.57.5-rev1.1`
- Add the `avd` directory, containing all validated AVD data models for `domain-a` to the `labs/techlib-vxlan-domain-a` directory

### Repository Checklist

- [ ] My code has been rebased from the upstream `main` branch

2024-11-18 12:57 UTC, ankudinov requested changes

2024-11-18 12:57 UTC, ankudinov commented on .devcontainer/techlib-vxlan-domain-a/devcontainer.json
> +    // "image": "ghcr.io/${localEnv:GITHUB_REPOSITORY}/lab-base:python3.11-avd-v5.0.0-clab0.57.5-rev1.1",
Rev1.1 is still being tested and mostly dedicated to acLabs templating functionality. It's functional, but will be replaced with 1.2 soon.

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/Makefile
Make file must be in the lab directory root as it must be available from the container workspace. Also Makefile for every lab will have a standard and templated layout in future shared by other labs. I'd suggest to keep existing Makefile for now and add AVD shortcuts there.

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/config_backup/A-LEAF1_post_running-config.conf
Everything in `avd/config_backup` must be gitignored. Example here: https://github.com/arista-netdevops-community/one-click-se-demos/blob/6bb2b2aabc02a98837af27ebcc3e4b4f1509111a/demos/cvaas-cvaas-and-avd-demo--evpn-mlag/.gitignore#L113

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/documentation/devices/A-LEAF1.md
I'd suggest to avoid generating AVD docs and configs in advance. That can be done when lab starts and keeps inventory compact. However it's just an opinion and adding files in advance has some minor advantages. For ex. it's easier to inspect inventory with running the lab.

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/DOMAIN_A_FABRIC.yml
> +###################################################
Custom structured section is quite long. Are we planning to advertise that as best practice for AVD data model? If yes, we have to sync with AVD maintainers team and find a better way to implement missing features. Otherwise we can consider dropping some non-essential configuration from custom structured section.

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/DOMAIN_A_FABRIC.yml
> +      structured_config:
This is quite advanced construct for most AVD users and will likely work with Ansible inventories only, not PyAVD directly. IMO, we should find a way to simplify that.

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/DOMAIN_A_FABRIC.yml
> +    loopback_ipv4_pool: 1.1.1.0/24
Let's swap to more realistic pools. Maybe 100.64 or similar.

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +management_api_http:
Are we going to recommend config different from the default AVD eAPI config?

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +mgmt_interface: Management0
This is set by specifying platform and must not be defined explicitely.

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +ip_ssh_client_source_interfaces:
Is this required?

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +ip_http_client_source_interfaces:
Is this required?

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +ip_domain_lookup:
Is this required?

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +event_monitor:
Is it something we are going to use in the lab?

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +# Clock Timezone
Remove or switch to UTC in my opinion.

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +ip_name_servers:
IIRC we have to use `name_servers`. `ip_name_servers` is low level var used by `eos_cli_config_gen`

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +management_ssh:
Do we need this?

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +avd_data_validation_mode: warning
I'd suggest changing avd_data_validation_mode to error.

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/intended/test_catalogs/A-LEAF1-catalog.yml
Do not add any ANTA generated files to the lab inventory by default. Especially result jsons.

2024-11-18 12:57 UTC, ankudinov commented on tech-library/datacenter/evpnvxlan/avd/domain-a/Makefile
Same as above - we should have one single Makefile in the container workspace.

2024-11-18 12:57 UTC, ankudinov commented on tech-library/datacenter/evpnvxlan/avd/domain-a/group_vars/DOMAIN_A_ENDPOINTS.yml
Why do we need duplicate files in tech-library/datacenter if we already have the in /labs ?

2024-11-18 12:57 UTC, ankudinov commented on labs/techlib-vxlan-domain-a/avd/inventory.yml
Is this the final structure of the inventory.yml ? Where are the management addresses?

2025-01-04 18:41 UTC, MitchV85 commented on labs/techlib-vxlan-domain-a/avd/Makefile
Done. `Makefile` moved to lab directory root.

2025-01-04 18:41 UTC, MitchV85 commented on labs/techlib-vxlan-domain-a/avd/config_backup/A-LEAF1_post_running-config.conf
Done. `avd/config_backup` added to `.gitignore`

2025-01-04 18:53 UTC, MitchV85 commented on labs/techlib-vxlan-domain-a/avd/documentation/devices/A-LEAF1.md
I like this - keeping the number of pre-built AVD-related files at a minimum will make it easier to maintain as AVD and labs evolve. Done.

2025-01-04 18:58 UTC, MitchV85 commented on labs/techlib-vxlan-domain-a/avd/group_vars/all.yml
> +avd_data_validation_mode: warning
Can't make this change until the per-MAC-VRF `evpn_l2_multi_domain` parameter is no longer erroneously considered a validation error.

2025-01-04 18:59 UTC, MitchV85 commented on tech-library/datacenter/evpnvxlan/avd/domain-a/Makefile
Done. Single `Makefile` exists at the lab directory root.

2025-01-04 19:01 UTC, MitchV85 commented on labs/techlib-vxlan-domain-a/avd/intended/test_catalogs/A-LEAF1-catalog.yml
Done.

2025-01-04 19:09 UTC, MitchV85 commented on labs/techlib-vxlan-domain-a/avd/group_vars/DOMAIN_A_FABRIC.yml
> +###################################################
Agreed on syncing with AVD team to help optimize or eliminate custom structured config from the data models. It's likely we will always have some level of custom structure config, and it's good to show this option; But we do want to keep it to a minimum.

2025-01-04 19:10 UTC, MitchV85 commented on labs/techlib-vxlan-domain-a/avd/inventory.yml
Because ContainerLab is awesome, it auto-creates the entries in `/etc/hosts` so there's no need to add the IP addresses to the inventory file. Keeping it lean/clean.

2025-01-05 00:02 UTC, merged